DB_NAME = "sentiment_data.db"

MAX_SENTENCE_LENGTH = 50

CORRECTION_DICT = {
    "k": "không",
    "ko": "không",
    "hok": "không",
    "khong": "không",
    "bt": "biết",
    "biet": "biết",
    "đc": "được",
    "dc": "được",
    "duoc": "được",
    "nhieu": "nhiều",
    "nhìu": "nhiều",
    "bth": "bình thường",
    "ae": "anh em",
    "gđ": "gia đình",
    "nyc": "người yêu cũ",
    "ntn": "như thế nào",
    "j": "gì",
    "v": "vậy",
    "vs": "với",
    "mn": "mọi người",
    "iu": "yêu",
    "hqa": "hôm qua",
    "hnay": "hôm nay",
    "rat": "rất",
    "toi": "tôi",
    "th": "thôi",
    "nhi": "nhỉ",
    "chan": "chán",
    "buon": "buồn",
    "buc": "bực",
    "tuc": "tức",
    "met": "mệt",
    "z": "vậy",
    "thuong": "thương",
    "ghet": "ghét",
    "e": "em",
    "a": "anh",
    "c": "chị",
    "hqua": "hôm qua",
    "di": "đi",
    "mò": "mà",
    "rùi": "rồi",
    "jz": "gì vậy",
    "m": "mày",
    "t": "tôi",
    "qtqd": "quá trời quá đất"
}